apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
    generateName: generator-argo-
    namespace: generator
spec:
    serviceAccountName: default
    entrypoint: pipeline

    arguments:
        parameters:
            -   name: cc
                value: "ee"
            -   name: org
                value: "has"
            -   name: uuid
                value: "427ae6c8-2d17-4e1c-be75-2c43883cdf95"

    templates:
        -   name: pipeline
            steps:
                -   -   name: make-working-dir
                        template: make-working-dir
                        arguments:
                            parameters:
                                -   name: cc
                                    value: "{{workflow.parameters.cc}}"
                                -   name: org
                                    value: "{{workflow.parameters.org}}"
                                -   name: uuid
                                    value: "{{workflow.parameters.uuid}}"

        -   name: make-working-dir
            inputs:
                parameters:
                    -   name: cc
                    -   name: org
                    -   name: uuid
            container:
                image: alpine
                securityContext:
                    privileged: true
                command: [ sh, -c ]
                args:
                    - |
                        set -e

                        CC="{{inputs.parameters.cc}}"
                        ORG="{{inputs.parameters.org}}"
                        UUID="{{inputs.parameters.uuid}}"
                        GINTRA_ROOT="/mnt/gintra"
                        ORG_ROOT="$GINTRA_ROOT/organizations/$CC/$ORG"
                        WORKFLOWS_DIR="$ORG_ROOT/workflows"
                        AI_DIR="$ORG_ROOT/ai"
                        WORKDIR="$WORKFLOWS_DIR/$UUID"
                        AI_WORKDIR="$AI_DIR/$UUID"

                        apk add --no-cache nfs-utils

                        mkdir -p "$GINTRA_ROOT"
                        mount -t nfs nfs-server-service.generator.svc.cluster.local:/ "$GINTRA_ROOT"

                        echo "Gintra root: $GINTRA_ROOT"
                        ls "$GINTRA_ROOT"
                        mkdir -p "$WORKFLOWS_DIR" "$AI_DIR"
                        ls "$ORG_ROOT"

                        mkdir -p "$WORKDIR"
                        mkdir -p "$AI_WORKDIR"
                        echo "Created: $WORKDIR"
                        ls "$WORKDIR"
                        echo "Created: $AI_WORKDIR"
                        ls "$AI_WORKDIR"
