apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: argo-nfs-shared-persistent-volume-claim
    namespace: argo
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: nfs
    resources:
        requests:
            storage: 5Gi
