apiVersion: apps/v1
kind: Deployment
metadata:
    name: xyz-deployment
    namespace: xyz-dev
    labels:
        app: xyz-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: xyz-deployment
    template:
        metadata:
            labels:
                app: xyz-deployment
        spec:
            containers:
                -   name: xyz
                    image: xyz:latest
                    # For example, not needed in Minikube
                    # imagePullPolicy: Never
                    ports:
                        -   name: xyz-port
                            containerPort: 8080
                    volumeMounts:
                        -   name: nfs-volume
                            mountPath: /mnt/gintra
                    env:
                        # For Spring boot
                        -   name: APPLICATION_PROFILES
                            value: "dev,api-docs"
                        ## From config-map
                        -   name: VARIABLE
                            valueFrom:
                                configMapKeyRef:
                                    name: xyz-config-map
                                    key: variable
                                    optional: false
                        -   name: POD_NAMESPACE
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.namespace
                        -   name: POD_NAME
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.name
                        -   name: NODE_NAME
                            valueFrom:
                                fieldRef:
                                    fieldPath: spec.nodeName
                        ## From secrets
                        -   name: SECRET_VARIABLE
                            valueFrom:
                                secretKeyRef:
                                    name: xyz-secrets-map
                                    key: secret-variable
                                    optional: false
            volumes:
                -   name: nfs-volume
                    persistentVolumeClaim:
                        claimName: xyz-nfs-persistent-volume-claim
