apiVersion: v1
kind: PersistentVolume
metadata:
    name: argo-host-path-persistent-volume
spec:
    capacity:
        storage: 5Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    storageClassName: manual
    hostPath:
        path: /var/opt/setmy.info/minikube
        type: DirectoryOrCreate
    persistentVolumeReclaimPolicy: Retain
