apiVersion: apps/v1
kind: Deployment
metadata:
    name: nfs-server
    namespace: argo
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nfs-server
    template:
        metadata:
            labels:
                app: nfs-server
        spec:
            containers:
                - name: nfs-server
                  image: itsthenetwork/nfs-server-alpine
                  securityContext:
                      privileged: true
                  env:
                      - name: SHARED_DIRECTORY
                        value: /exports
                  ports:
                      - containerPort: 2049
