apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-shared-pv
spec:
    capacity:
        storage: 5Gi
    accessModes:
        - ReadWriteMany
    nfs:
        server: nfs-server.argo.svc.cluster.local
        path: /
    persistentVolumeReclaimPolicy: Retain
