apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nfs-shared-pvc
    namespace: argo
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 5Gi
